name: "Build Docs"
on: 
- pull_request
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Sphinx
      run: sudo apt-get update && sudo apt-get install python3-sphinx -y
    - name: Install furo theme and nox tool from PyPI
      run: pip3 install furo nox
    - name: Build Sphinx docs
      run: nox -s docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/docs
        name: docs
    - name: Uninstall Sphinx
      run: sudo apt-get purge python3-sphinx -y
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
           name: docs
           path: ${{ github.workspace }}/doc-build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: doc-build # The folder the action should deploy.
