name: "Build Docs"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Sphinx
      run: sudo apt-get update && sudo apt-get install python3-sphinx -y
    - name: Install furo theme from PyPI
      run: pip3 install furo
    - name: Build Sphinx docs
      run: make html -C documentation
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: documentation/build/html # The folder the action should deploy.
    - name: Uninstall Sphinx
      run: sudo apt-get purge python3-sphinx -y
