name: "Build Docs"
on: 
- pull_request
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Sphinx
      run: sudo apt-get update && sudo apt-get install -y python3-sphinx
    - name: Install furo theme and nox tool from PyPI
      run: pip3 install furo nox
    - name: Install Sphinx tab/design extension
      run: pip3 install sphinx-inline-tabs sphinx-design
    - name: Build Sphinx docs
      run: nox -s docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/docs
        name: docs
    - name: Uninstall Sphinx
      run: sudo dpkg --purge python3-sphinx
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
           name: docs
           path: ${{ github.workspace }}/doc-build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc-build # The folder the action should deploy.
